### ISSUE TITLE
Need *.doc filenames for publication 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parser-rosstat-isep#6]
https://github.com/mini-kep/parser-rosstat-isep/blob/0335a2d503d900633b97b1733fdaaf3a4ff1c0e3/getter.py#L59-L60

**Comment by lynxrv21** [comment]
Full list of filenames:
`['1-0', '2-1', '2-1-0', '2-1-1', '2-1-2', '2-1-3', '2-1-4', '2-2-0', '2-2-1', '2-2-2', '2-2-3', '2-2-4', '2-3', '2-3-1', '2-3-2', '2-4', '2-5', '3-1', '3-2', '4-0', '4-1', '4-2', '5-0', '6-0', '7-0', '8-0']`

**Comment by epogrebnyak** [comment]
below is listing date-filename and file size:
```
2017 10 1-0 219
2017 10 2-1 0
2017 10 2-1-0 233
2017 10 2-1-1 234
2017 10 2-1-2 1758
2017 10 2-1-3 235
2017 10 2-1-4 210
2017 10 2-2-0 0
2017 10 2-2-1 554
2017 10 2-2-2 402
2017 10 2-2-3 0
2017 10 2-2-4 1
2017 10 2-3 516
2017 10 2-3-1 1
2017 10 2-3-2 0
2017 10 2-4 464
2017 10 2-5 0
2017 10 3-1 563
2017 10 3-2 733
2017 10 4-0 354
2017 10 4-1 676
2017 10 4-2 573
2017 10 5-0 477
2017 10 6-0 804
2017 10 7-0 404
2017 10 8-0 558
```
Zero size means there is no such file on this date. Does this mean this file exists for other dates, or it is put in error?

**Comment by epogrebnyak** [comment]
Link like <http://www.gks.ru/bgd/free/B17_00/IssWWW.exe/Stg/dk09/2-1.doc> in 2017-09 changes some points in numbering.  It is not present in 2017-10
